# operation_pattern:
#   type: constant
#   operation: read

# operation_pattern:
#   type: constant
#   operation: write

# operation_pattern:
#   type: percentage
#   read_percentage: 60 

operation_pattern:
  type: mixed
  pattern:
    - read
    - read
    - write
    - write
    - write
    - read
    - read

# access_pattern:
#   type: sequential
#   block_size: 4096
#   limit: 65536

# access_pattern:
#   type: random
#   block_size: 2
#   limit: 10

access_pattern:
  type: zipfian
  block_size: 2
  limit: 65536
  skew: 0.2

